### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rdnfn** [rdnfn/bauwerk#3]
This issue tracks a preliminary roadmap of bauwerk. Not all features here will likely be implemented. The order of list elements indicates the priority (for each list, not between lists).

## Env features
- [ ] Support (optional) selling energy to grid
- [ ] Support sampling environment from env distributions (defined over env parameters)
- [ ] Add tests that verify equivalency to mathematical CVXPY formulation

## Game features
- [ ] Add time of day and date to game interface
- [ ] Fix axis to avoid confusion as viewed data range changes
- [ ] Add configuration controls to UI
- [ ] Slow down default speed in game
- [ ] Improve human interpretability of reward/score (change scale, add currency sign, enable positive rewards)
- [ ] Change front to monospace across game interface
- [ ] Add support to set sizing parameters in game
- [ ] Add HVAC simulation

## Docs
- [ ] Add mathematical description of problem

## Experiments
- [ ] Add basic experiments with standard RL methods
